/**
 * Transcript Generator
 * Creates HTML transcripts of messages for audit purposes
 */

const fs = require('fs');
const path = require('path');

const TRANSCRIPT_DIR = path.join(__dirname, '..', 'data', 'transcripts');

// Ensure transcript directory exists
if (!fs.existsSync(TRANSCRIPT_DIR)) {
    fs.mkdirSync(TRANSCRIPT_DIR, { recursive: true });
}

/**
 * Generate HTML transcript from messages
 */
function generateTranscript(messages, metadata = {}) {
    const sortedMessages = [...messages].sort((a, b) => a.createdTimestamp - b.createdTimestamp);

    const html = `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Message Transcript - ${metadata.channelName || 'Unknown Channel'}</title>
  <style>
    * { box-sizing: border-box; margin: 0; padding: 0; }
    body {
      font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, 'Helvetica Neue', Arial, sans-serif;
      background-color: #36393f;
      color: #dcddde;
      padding: 20px;
    }
    .header {
      background: #2f3136;
      border-radius: 8px;
      padding: 20px;
      margin-bottom: 20px;
      border-left: 4px solid #5865f2;
    }
    .header h1 { color: #fff; margin-bottom: 10px; font-size: 20px; }
    .header-info { color: #8e9297; font-size: 14px; line-height: 1.6; }
    .header-info span { color: #fff; }
    .messages { max-width: 900px; }
    .message {
      display: flex;
      padding: 8px 16px;
      margin-bottom: 1px;
    }
    .message:hover { background: rgba(4,4,5,0.07); }
    .message-group-start { margin-top: 16px; }
    .avatar {
      width: 40px;
      height: 40px;
      border-radius: 50%;
      margin-right: 16px;
      flex-shrink: 0;
      background: #5865f2;
      display: flex;
      align-items: center;
      justify-content: center;
      color: #fff;
      font-weight: bold;
      font-size: 16px;
    }
    .avatar img { width: 100%; height: 100%; border-radius: 50%; }
    .content { flex: 1; min-width: 0; }
    .header-row { display: flex; align-items: baseline; }
    .username { color: #fff; font-weight: 500; font-size: 16px; margin-right: 8px; }
    .bot-tag {
      background: #5865f2;
      color: #fff;
      font-size: 10px;
      padding: 1px 4px;
      border-radius: 3px;
      margin-right: 8px;
      font-weight: 600;
    }
    .timestamp { color: #72767d; font-size: 12px; }
    .text { color: #dcddde; line-height: 1.4; word-wrap: break-word; margin-top: 2px; }
    .attachment {
      margin-top: 8px;
      padding: 10px;
      background: #2f3136;
      border-radius: 4px;
      border: 1px solid #202225;
    }
    .attachment a { color: #00aff4; text-decoration: none; }
    .attachment a:hover { text-decoration: underline; }
    .embed {
      max-width: 520px;
      margin-top: 8px;
      padding: 12px;
      background: #2f3136;
      border-radius: 4px;
      border-left: 4px solid #5865f2;
    }
    .embed-title { color: #fff; font-weight: 600; margin-bottom: 8px; }
    .embed-description { color: #dcddde; font-size: 14px; }
    .footer {
      margin-top: 30px;
      padding: 20px;
      background: #2f3136;
      border-radius: 8px;
      text-align: center;
      color: #72767d;
      font-size: 12px;
    }
  </style>
</head>
<body>
  <div class="header">
    <h1>📝 Message Transcript</h1>
    <div class="header-info">
      <div><strong>Server:</strong> <span>${escapeHtml(metadata.guildName || 'Unknown')}</span></div>
      <div><strong>Channel:</strong> <span>#${escapeHtml(metadata.channelName || 'Unknown')}</span></div>
      <div><strong>Messages:</strong> <span>${sortedMessages.length}</span></div>
      <div><strong>Generated:</strong> <span>${new Date().toISOString()}</span></div>
      ${metadata.moderator ? `<div><strong>Purged By:</strong> <span>${escapeHtml(metadata.moderator)}</span></div>` : ''}
      ${metadata.reason ? `<div><strong>Reason:</strong> <span>${escapeHtml(metadata.reason)}</span></div>` : ''}
    </div>
  </div>
  
  <div class="messages">
${sortedMessages.map((msg, i) => renderMessage(msg, i === 0 || msg.author.id !== sortedMessages[i - 1]?.author.id)).join('\n')}
  </div>
  
  <div class="footer">
    Generated by Government Utilities Bot • ${new Date().toLocaleDateString()}
  </div>
</body>
</html>`;

    return html;
}

/**
 * Render a single message to HTML
 */
function renderMessage(msg, showHeader) {
    const timestamp = new Date(msg.createdTimestamp).toLocaleString();
    const initial = msg.author.username.charAt(0).toUpperCase();
    const avatarUrl = msg.author.displayAvatarURL({ size: 64 });

    let content = escapeHtml(msg.content || '');

    // Convert mentions to readable format
    content = content.replace(/&lt;@!?(\d+)&gt;/g, '@user');
    content = content.replace(/&lt;#(\d+)&gt;/g, '#channel');
    content = content.replace(/&lt;@&amp;(\d+)&gt;/g, '@role');

    // Convert line breaks
    content = content.replace(/\n/g, '<br>');

    let html = `    <div class="message${showHeader ? ' message-group-start' : ''}">`;

    if (showHeader) {
        html += `
      <div class="avatar">
        <img src="${avatarUrl}" onerror="this.style.display='none'; this.parentElement.innerHTML='${initial}';">
      </div>
      <div class="content">
        <div class="header-row">
          <span class="username">${escapeHtml(msg.author.username)}</span>
          ${msg.author.bot ? '<span class="bot-tag">BOT</span>' : ''}
          <span class="timestamp">${timestamp}</span>
        </div>
        <div class="text">${content || '<em>No text content</em>'}</div>`;
    } else {
        html += `
      <div class="avatar" style="visibility: hidden;"></div>
      <div class="content">
        <div class="text">${content || '<em>No text content</em>'}</div>`;
    }

    // Attachments
    if (msg.attachments.size > 0) {
        for (const [, att] of msg.attachments) {
            html += `
        <div class="attachment">
          📎 <a href="${att.url}" target="_blank">${escapeHtml(att.name)}</a> (${formatBytes(att.size)})
        </div>`;
        }
    }

    // Embeds
    if (msg.embeds.length > 0) {
        for (const embed of msg.embeds) {
            html += `
        <div class="embed">
          ${embed.title ? `<div class="embed-title">${escapeHtml(embed.title)}</div>` : ''}
          ${embed.description ? `<div class="embed-description">${escapeHtml(embed.description).substring(0, 200)}${embed.description.length > 200 ? '...' : ''}</div>` : ''}
        </div>`;
        }
    }

    html += `
      </div>
    </div>`;

    return html;
}

/**
 * Escape HTML characters
 */
function escapeHtml(text) {
    if (!text) return '';
    return text
        .replace(/&/g, '&amp;')
        .replace(/</g, '&lt;')
        .replace(/>/g, '&gt;')
        .replace(/"/g, '&quot;')
        .replace(/'/g, '&#039;');
}

/**
 * Format bytes to human readable
 */
function formatBytes(bytes) {
    if (!bytes) return '0 B';
    const k = 1024;
    const sizes = ['B', 'KB', 'MB', 'GB'];
    const i = Math.floor(Math.log(bytes) / Math.log(k));
    return parseFloat((bytes / Math.pow(k, i)).toFixed(2)) + ' ' + sizes[i];
}

/**
 * Save transcript to file and return path
 */
function saveTranscript(html, filename) {
    const filePath = path.join(TRANSCRIPT_DIR, filename);
    fs.writeFileSync(filePath, html, 'utf8');
    return filePath;
}

module.exports = {
    generateTranscript,
    saveTranscript,
    TRANSCRIPT_DIR
};
